[project]
name = 'memegoat-liquidity-locker'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

# [[project.requirements]]
# contract_id = 'SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.trait-sip-010'

# [[project.requirements]]
# contract_id = 'SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.trait-semi-fungible'


# [[project.requirements]]
# contract_id = 'SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.amm-swap-pool-v1-1'

# [[project.requirements]]
# contract_id = 'SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.token-amm-swap-pool-v1-1'


# [contracts.memegoat-locker-mainnet]
# path = 'contracts/locker.clar'
# depends_on = [ "trait-sip-010" ]
# clarity_version = 2
# epoch = 2.4


[contracts.alex-vault-v1-1]
path = 'contracts/test-contracts/alex-vault-v1-1.clar'
clarity_version = 2
epoch = 2.4

[contracts.amm-swap-pool-v1-1]
path = 'contracts/test-contracts/amm-swap-pool-v1-1.clar'
clarity_version = 2
epoch = 2.4

# [contracts.memegoat-faucet-v1]
# path = 'contracts/test-contracts/faucet.clar'
# clarity_version = 2
# epoch = 2.4

[contracts.memegoat-launchpad-v1]
path = 'contracts/launchpad.clar'
clarity_version = 2
epoch = 2.4

[contracts.memegoat-launchpad-ext-v1]
path = 'contracts/launchpad-ext.clar'
clarity_version = 2
epoch = 2.4

[contracts.memegoat-launchpad-v1-1]
path = 'contracts/launchpad-v1-1.clar'
clarity_version = 2
epoch = 2.4

[contracts.memegoat-distributor-v2]
path = 'contracts/distributor.clar'
clarity_version = 2
epoch = 2.4

[contracts.memegoat-staking-v1]
path = 'contracts/staking.clar'
clarity_version = 2
epoch = 2.4

[contracts.memegoat-token-locker-v1]
path = 'contracts/token-locker.clar'
clarity_version = 2
epoch = 2.4

[contracts.memegoat-liquidity-locker-v1]
path = 'contracts/liquidity-locker.clar'
clarity_version = 2
epoch = 2.4

[contracts.memegoat-vault-v1]
path = 'contracts/vault.clar'
clarity_version = 2
epoch = 2.4

[contracts.memegoatstx]
path = 'contracts/test-contracts/token/memegoatstx.clar'
clarity_version = 2
epoch = 2.4

[contracts.testSTX]
path = 'contracts/test-contracts/token/testSTX.clar'
clarity_version = 2
epoch = 2.4

[contracts.token-amm-swap-pool-v1-1]
path = 'contracts/test-contracts/token-amm-swap-pool-v1-1.clar'
clarity_version = 2
epoch = 2.4

[contracts.trait-flash-loan-user]
path = 'contracts/test-contracts/traits/trait-flash-loan-user.clar'
clarity_version = 1
epoch = 2.05

[contracts.trait-ownable]
path = 'contracts/traits/trait-ownable.clar'
clarity_version = 1
epoch = 2.05

[contracts.trait-semi-fungible]
path = 'contracts/traits/trait-semi-fungible.clar'
clarity_version = 1
epoch = 2.05

[contracts.trait-sip-010]
path = 'contracts/traits/trait-sip-010.clar'
clarity_version = 1
epoch = 2.05

[repl]
clarity_wasm_mode = false
show_timings = false

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
